version: "3.9"

x-logging:
  &highlight-logging
    driver: fluentd
    options:
      fluentd-address: "tls://otel.highlight.io:24284"
      fluentd-async: "true"
      fluentd-sub-second-precision: "true"
      tag: "highlight.project_id=5g52kp4g"

services:
  stuttgart-gophers:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    logging: *highlight-logging
    ports:
    - "5000:5000"
 

    