version: '3'

tasks:
  build:
    cmds:
      - go build -o bin/StuttgartGophers
    silent: true

  run: 
    cmds:
      - ./bin/StuttgartGophers
    silent: true
    deps: [build]

  # test:
  #   cmds:
  #     - go test -v ./...
  #   silent: true